# Generated by Django 3.2.25 on 2026-06-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=500)),
                ('question_uz', models.CharField(blank=True, max_length=500)),
                ('question_en', models.CharField(blank=True, max_length=500)),
                ('answer_ru', models.TextField()),
                ('answer_uz', models.TextField(blank=True)),
                ('answer_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ekran nomi (RU)', max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(help_text="To'liq manzil")),
                ('location_uz', models.TextField(blank=True)),
                ('location_en', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, help_text='Tuman nomi (modalda chiqadi)', max_length=255)),
                ('size', models.CharField(help_text='Masalan: 48×8 м', max_length=50)),
                ('format', models.CharField(blank=True, help_text="Tag (size bilan bir xil bo'lishi mumkin)", max_length=50)),
                ('type_display', models.CharField(default='LED', max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('broadcast_hours', models.CharField(default='06:00–00:00', max_length=50)),
                ('category', models.CharField(choices=[('super', 'Super Format'), ('city', 'City'), ('district', 'District')], default='city', max_length=20)),
                ('status', models.CharField(choices=[('live', 'LIVE'), ('soon', 'СКОРО')], default='live', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monitors/')),
                ('video', models.FileField(blank=True, null=True, upload_to='monitors/videos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Asosiy 'Suparformat' gridda chiqadi")),
                ('is_in_ticker', models.BooleanField(default=True, help_text='Yuqoridagi ticker chiziqda chiqadi')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+998 94 657-33-33', max_length=50)),
                ('email', models.EmailField(default='info@ahadmix.uz', max_length=254)),
                ('address_ru', models.CharField(default='г. Ташкент, проспект Бунёдкора, 8а', max_length=255)),
                ('address_uz', models.CharField(default="Toshkent sh., Bunyodkor shoh ko'chasi, 8a", max_length=255)),
                ('address_en', models.CharField(default='Tashkent, Bunyodkor avenue 8a', max_length=255)),
                ('telegram_link', models.URLField(default='https://linktr.ee/ahadmix_group')),
                ('screens_count', models.PositiveIntegerField(default=70)),
                ('years_on_market', models.PositiveIntegerField(default=16)),
                ('brand_partners_count', models.PositiveIntegerField(default=500)),
                ('kp_pdf', models.FileField(blank=True, help_text='Tijorat taklifi PDF (КП)', null=True, upload_to='docs/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatisticCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('plus', models.BooleanField(default=False, help_text="Sonidan keyin '+' chiqsinmi")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(help_text="To'liq <svg>...</svg> kodi")),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MonitorPriceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(help_text='Masalan: 10 сек', max_length=50)),
                ('plays_per_month', models.CharField(help_text="Oyiga ko'rsatishlar soni", max_length=50)),
                ('price', models.CharField(help_text="Faqat raqam, 'сум' template'da qo'shiladi", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rows', to='common.monitor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
