# Generated by Django 3.2.25 on 2026-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
