# Generated by Django 3.2.25 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_outdoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='count',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
