# Generated by Django 3.2.25 on 2026-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20260618_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='count',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
