# Generated by Django 3.2.25 on 2026-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20260618_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
