# Generated by Django 3.2.25 on 2026-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20260619_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='steps',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
