# Generated by Django 3.2.25 on 2026-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20260620_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='card',
            name='steps',
        ),
        migrations.AddField(
            model_name='outdoor',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='outdoor',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
