# Generated by Django 3.2.25 on 2026-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20260620_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.RemoveField(
            model_name='outdoor',
            name='description',
        ),
        migrations.AddField(
            model_name='outdoor',
            name='steps',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
