# Generated by Django 3.2.25 on 2026-06-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20260622_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='led_screens/')),
                ('screen_size', models.CharField(max_length=20)),
                ('resolution', models.CharField(max_length=20)),
                ('broadcast_time', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('screen_format', models.CharField(default='Стандартный формат', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(blank=True, help_text="Agar rasm sifatida icon yuklamoqchi bo'lsangiz, shu yerga yuklang", null=True, upload_to='why_us_icons/', verbose_name='Icon rasm (ixtiyoriy)')),
                ('icon_class', models.CharField(blank=True, help_text="Masalan: 'map-pin', 'globe' — icon font ishlatilsa shu yerga yoziladi", max_length=100, verbose_name='Icon nomi (ixtiyoriy)')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kichik raqam birinchi chiqadi (0, 1, 2, 3...)', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (saytda ko'rinadi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karta (Nima uchun AHADMIX)',
                'verbose_name_plural': 'Kartalar (Nima uchun AHADMIX)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('views_per_month', models.PositiveIntegerField(default=9000)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('led_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='common.monitor')),
            ],
        ),
    ]
