# Generated by Django 3.2.25 on 2026-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_monitor_pricepackage_whyuscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyuscard',
            name='icon_svg',
            field=models.TextField(blank=True, help_text="To'liq <svg>...</svg> kodini shu yerga joylashtiring", verbose_name='Icon SVG kodi (ixtiyoriy)'),
        ),
    ]
