# Generated by Django 3.2.25 on 2026-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_whyuscard_icon_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
