# Generated by Django 3.2.25 on 2026-06-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_processcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveIntegerField()),
                ('plus', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
