# Generated by Django 3.2.25 on 2026-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_statisticcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='led_screens/videos/'),
        ),
    ]
